In [5]:
import pandas as pd

data = pd.read_csv("./105.csv")

data

,Access,CT du lieu,CT may tinh,CNXHKH,Chuyen de,CS du lieu,Cong nghe NET,CNphan mem,Dai so so hoc,DS tuyen tinh,...,Toan roi rac,Tri tue nhan tao,Triet hoc 1,Triet hoc 2,TT Ho Chi Minh,VL Dai cuong 1,VL Dai cuong 2,Visual Basic,Xac suat,Unnamed: 55
0,9.0,9.0,7.0,9.0,8.0,10.0,NaN,9.0,7.0,10.0,...,8.0,9.0,8.0,7.0,NaN,9.0,7.0,10.0,8.0,NaN
1,6.0,8.0,6.0,7.0,8.0,5.0,NaN,8.0,5.0,7.0,...,6.0,8.0,6.0,6.0,NaN,9.0,7.0,5.0,5.0,NaN
2,7.0,8.0,7.0,5.0,7.0,5.0,NaN,7.0,7.0,10.0,...,8.0,5.0,8.0,6.0,NaN,8.0,8.0,10.0,5.0,NaN
3,5.0,6.0,5.0,7.0,3.0,5.0,NaN,5.0,5.0,7.0,...,6.0,5.0,6.0,5.0,NaN,3.0,5.0,6.0,5.0,NaN
4,5.0,8.0,5.0,7.0,6.0,6.0,NaN,6.0,6.0,5.0,...,5.0,5.0,8.0,5.0,NaN,6.0,7.0,6.0,6.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,NaN,6.0,6.0,7.0,6.0,8.0,6.0,8.0,7.0,5.0,...,6.0,8.0,5.0,6.0,6.0,7.0,6.0,5.0,5.0,5.0
95,NaN,5.0,7.0,6.0,8.0,7.0,7.0,7.0,7.0,5.0,...,9.0,5.0,5.0,7.0,5.0,6.0,6.0,5.0,9.0,7.0
96,NaN,7.0,7.0,8.0,8.0,9.0,8.0,8.0,8.0,9.0,...,9.0,9.0,8.0,8.0,8.0,9.0,9.0,9.0,10.0,7.0
97,NaN,7.0,5.0,5.0,6.0,9.0,6.0,6.0,8.0,6.0,...,7.0,5.0,6.0,6.0,5.0,7.0,5.0,7.0,6.0,9.0
98,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.0

Rời rạc hóa các trường trong tệp dữ liệu điểm 105.csv thành 0,1 (0 cho những
giá trị điểm >=6, 0 cho những giá trị còn lại) Lưu lại thành file 105moi.csv

In [10]:
data_col = data.columns.tolist()
print(data_col)

['Access', 'CT du lieu', 'CT may tinh', 'CNXHKH', 'Chuyen de ', 'CS du lieu', 'Cong nghe NET ', 'CNphan mem', 'Dai so so hoc', 'DS tuyen tinh', 'Dan so', 'Do an', 'Do hoa', 'Foxpro', 'Giai tich 1', 'Giai tich 2', 'Giai tich so', 'He dieu hanh ', 'He Quan tri CSDL1 ', 'He Quan tri CSDL2 ', 'Hinh giai tich', 'Hop ngu', 'Kinh te chinh tri', 'Ky thuat lap trinh', 'LT huong doi tuong', 'Lich su Dang', 'Logic toan ', 'Mang may tinh', 'NN hinh thuc', 'Ngon ngu C', 'NM phap luat', 'NM thuat toan', 'Pascal nang cao', 'PTTKHT', 'TK ung dung', 'TH he quan tri CSDL1', 'TH Ngon ngu C', 'TH nang cao3', 'Tieng Anh 1', 'Tieng Anh 2', 'Tieng Anh 3', 'Tieng Anh 4', 'Tieng Anh 5', 'Tieng Anh 6', 'TH dai cuong 2', 'TH dai cuong 1', 'Toan roi rac', 'Tri tue nhan tao', 'Triet hoc 1', 'Triet hoc 2', 'TT Ho Chi Minh', 'VL Dai cuong 1', 'VL Dai cuong 2', 'Visual Basic', 'Xac suat', 'Unnamed: 55']

In [11]:
# Xoá cột Unnamed: 55
data = data.drop(columns=['Unnamed: 55'])

# Định nghĩa hàm lambda để rời rạc hóa các giá trị điểm
f = lambda x: 1 if x >=6 else 0

# Rời rạc hóa tất cả các trường dữ liệu bằng phương thức applymap
data_roirac = data.applymap(f)

data_roirac.to_csv('105moi.csv', index=False)

In [12]:
data2 = pd.read_csv('./105moi.csv')
data2

,Access,CT du lieu,CT may tinh,CNXHKH,Chuyen de,CS du lieu,Cong nghe NET,CNphan mem,Dai so so hoc,DS tuyen tinh,...,TH dai cuong 1,Toan roi rac,Tri tue nhan tao,Triet hoc 1,Triet hoc 2,TT Ho Chi Minh,VL Dai cuong 1,VL Dai cuong 2,Visual Basic,Xac suat
0,1,1,1,1,1,1,0,1,1,1,...,1,1,1,1,1,0,1,1,1,1
1,1,1,1,1,1,0,0,1,0,1,...,1,1,1,1,1,0,1,1,0,0
2,1,1,1,0,1,0,0,1,1,1,...,1,1,0,1,1,0,1,1,1,0
3,0,1,0,1,0,0,0,0,0,1,...,1,1,0,1,0,0,0,0,1,0
4,0,1,0,1,1,1,0,1,1,0,...,0,0,0,1,0,0,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,0,1,1,1,1,1,1,1,1,0,...,1,1,1,0,1,1,1,1,0,0
95,0,0,1,1,1,1,1,1,1,0,...,1,1,0,0,1,0,1,1,0,1
96,0,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
97,0,1,0,0,1,1,1,1,1,1,...,0,1,0,1,1,0,1,0,1,1
98,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0