In [3]:
import pandas as pd

# Đọc file dữ liệu 105.csv
data = pd.read_csv('105.csv')

# Sử dụng hàm apply() để chuyển đổi từng cột về dạng true, false
data_tf = data.apply(lambda x: ~x.isna())

# Lưu kết quả vào file 105_tf.csv
data_tf.to_csv('105_tf.csv', index=False)

Thực hiện chuyển dổi cho file dữ liệu 105.csv về dạng true, false. (true
cho những cột có điểm, false cho những cột không có điểm)

In [4]:
data2 = pd.read_csv('105_tf.csv')
data2

,Access,CT du lieu,CT may tinh,CNXHKH,Chuyen de,CS du lieu,Cong nghe NET,CNphan mem,Dai so so hoc,DS tuyen tinh,...,Toan roi rac,Tri tue nhan tao,Triet hoc 1,Triet hoc 2,TT Ho Chi Minh,VL Dai cuong 1,VL Dai cuong 2,Visual Basic,Xac suat,Unnamed: 55
0,True,True,True,True,True,True,False,True,True,True,...,True,True,True,True,False,True,True,True,True,False
1,True,True,True,True,True,True,False,True,True,True,...,True,True,True,True,False,True,True,True,True,False
2,True,True,True,True,True,True,False,True,True,True,...,True,True,True,True,False,True,True,True,True,False
3,True,True,True,True,True,True,False,True,True,True,...,True,True,True,True,False,True,True,True,True,False
4,True,True,True,True,True,True,False,True,True,True,...,True,True,True,True,False,True,True,True,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,False,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
95,False,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
96,False,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
97,False,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
98,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True